name: CI

on: 
 push:
   branches: [main]
 pull_request:
   branches: [main]

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: action/checout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //...
      - run: bazel test //...

        
